### ISSUE TITLE
신규 패시브&액티브 아이템

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Redrawn_Hard#14]
●해당 아이템들이 신규 항목으로 업데이트 됩니다
- [x] #Fallen Orb(타락한 오브) : 퀄리티 0,4가 등장하지 않으며, 2퀄리티 등장 시 20% 확률로 리롤됩니다

- [x] #Trinity(삼위일체) : 보스방 클리어 시 더 바디, 더 소울, 더 마인드를 제거합니다. 스테이지 입장 시 마다 더 바디, 더 소울, 더 마인드, 소지한 아이템 중 한가지가 소환되며, 4가지중 한가지 아이템을 획득하면 나머지는 사라집니다

- [x] #21
└출혈은 뒤치기 패시브 효과와 동일

- [x] #Divine Light(신의 조명) : 공격 시 확률적으로 빛줄기가 적용됩니다 (기본 10%, 럭1당10%p증가)

- [x] #Omega 321(오메가 321) : 방 입장 시 몬스터에게 둔화가 적용됩니다 
└방 들어가자마자 모래시계 발동시키게 하면됨

- [x] #Reincarnation(리인카네이션) : 다음 게임 시작 시 #CLICKER(c482) 소환됩니다

- [x] #Acute Sinusitis(급성 부비동염) : 공격 시 확률적으로 접착 눈물이 나갑니다 (기본 10%, 럭1당 2%p 증가)

- [x] #Laniakea Supercluster(라니아케아 초은하단) : 사용 시 모든 행성방 배열이 존재하는 방으로 이동됩니다
└울그로 이동되는 그리드 아이템처럼 행성방 0번으로 이동하면 됨. 참고로 액티브는 소모성 아니니까 삭제 ㄴㄴ

- [x] #Clover(클로버) : 럭 수치에 비례하여 공격력이 증가됩니다 (럭1당 공격력 2%p 증가), 소지 시 럭 1 증가

- [x] #Galactic Medal Of Valo(은하 용맹 훈장) : 보스 공격 시 30% 추가 데미지가 적용됩니다

- [x] #Pirate Map(해적의 지도) : 현재 스테이지에서 랜덤한 방 위치 2개를 보여주며, 럭 2당 1개의 방을 추가적으로 보여줍니다

- [x] #26

- [x] #Quasar(퀘이사) : 방 입장 시 처음으로 죽은 몬스터 위치에 #BLACK_HOLE(c512) 효과 발동

**Comment by pdom0327** [comment]
- Fallen Orb: 리롤된 아이템은 배열에서 제거 되나요?
- Trinity: 소지한 더 바디, 더 소울, 더 마인드를 제거하나요? 배열에서 제거하나요?
- Blood Of Hatred: (보류) 관련 상태이상 코드를 못찾겠습니다.
- Morphine: 최소 4번 공격하면 빠가지를 죽일 수 있는건가요?

**Comment by iwt2hw** [comment]
Fallen Orb: 일단 1차적으로 원하는 방식은 일단 오브랑 같음 일반 오브는 0,1 완전히 지우는데 폴린 오브도 마찬가지로 0,4는 완전히 지우고, 2퀄리티 등장 시 20% 확률로 다이스 발동임.이 과정에서 일반 오브의 경우 실제 배열을 지우지 않는걸로 아는데 지워져도 상관 없음

Trinity: 소지한 아이템 유무 상관없이 그냥 보스방 클리어 시 캐릭터에게 더바디, 더소울, 더마인드 -1 개 코드주면됨 + 추가적으로 배열의 경우 삼위일체 먹는 순간 제거

Morphine: 아 해당 아이템은 빠가지는 예외 처리
