### ISSUE TITLE
밸런스 : 작아지는 알약 제거

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Redrawn_Hard#17]
안나오게 해도 되고, 어떤 방식으로든 게임에서 작아지는 알약 사용 불가

**Comment by pdom0327** [comment]
작아지는 알약이 등장할 때 다른 효과로 변경할 수 있습니다.

1. 다른 효과로 랜덤 변경 (오리지널 로직과 다를 수 있음)
2. 무효과 알약으로 강제 변경

**Comment by iwt2hw** [comment]
1. 그렇다면 흡수 알약으로 변경
