### ISSUE TITLE
신규 장신구

### ISSUE THREAD

**Issue by iwt2hw** [TeamHY/Redrawn_Hard#19]
【장신구】
#Black Mirror(블랙 미러) : 획득 시 즉시 흡수되며, 패시브 아이템 획득 시 +1개가 더 추가됩니다. 아이템이 추가된 후 해당 장신구는 제거됩니다

**Comment by pdom0327** [comment]
컬렉터블과 다른 장신구의 특성이 사라지니까 즉시 흡수는 제거하는게 좋지않을까요? 황금 효과로 하거나요

**Comment by iwt2hw** [comment]
아이템과 장신구의 차이는 이미 배열 존재의 유무로 충분하다고 생각함

바로 흡수를 내장한 이유는, 즉시 흡수가 없으면 저거 버리기 컨으로 원하는 아이템 복사하는거 방지용
